apiVersion: apps/v1
kind: Deployment
metadata:
  name: awardit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awardit-api
  template:
    metadata:
      labels:
        app: awardit-api
    spec:
      containers:
        - name: awardit-api
          image: awardit-api:dev
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: awardit-api-service
spec:
  type: NodePort
  selector:
    app: awardit-api
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32001

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ExternalName
  externalName: 192.168.1.98 # Replace with the host IP (e.g., 192.168.x.x)
  ports:
    - protocol: TCP
      port: 5432 # The port your PostgreSQL instance is listening on
      targetPort: 5432
